-- =====================================================
-- Smart Profile Caching for Efficient Mission Generation
-- Version: 1.0.0
-- Date: June 2025
-- Description: Cache processed profiles to optimize LLM token usage
-- =====================================================

-- Create a table to store processed user profiles for LLM efficiency
CREATE TABLE user_profile_cache (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Processed profile summaries (ready for LLM)
    music_profile_summary TEXT,
    food_profile_summary TEXT,
    movie_profile_summary TEXT,
    relationship_insights TEXT,
    personality_summary TEXT,
    
    -- Behavioral insights
    mission_performance_summary TEXT,
    engagement_patterns TEXT,
    discovery_style TEXT,
    
    -- Context for smart invalidation
    data_version INTEGER DEFAULT 1,
    last_taste_update TIMESTAMP WITH TIME ZONE,
    last_people_update TIMESTAMP WITH TIME ZONE,
    last_behavior_update TIMESTAMP WITH TIME ZONE,
    
    -- Cache metadata
    cache_hits INTEGER DEFAULT 0,
    tokens_saved INTEGER DEFAULT 0,
    last_used_at TIMESTAMP WITH TIME ZONE,
    
    UNIQUE(user_id)
);

-- Index for efficient lookups
CREATE INDEX idx_user_profile_cache_user_id ON user_profile_cache(user_id);
CREATE INDEX idx_user_profile_cache_updated_at ON user_profile_cache(updated_at);

-- Function to intelligently invalidate cache when user data changes
CREATE OR REPLACE FUNCTION invalidate_profile_cache_on_data_change()
RETURNS TRIGGER AS $$
BEGIN
    -- Update the cache to mark it as stale
    UPDATE user_profile_cache 
    SET data_version = data_version + 1
    WHERE user_id = COALESCE(NEW.user_id, OLD.user_id);
    
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Apply triggers to invalidate cache when relevant data changes
CREATE TRIGGER trigger_invalidate_cache_on_people_change
    AFTER INSERT OR UPDATE OR DELETE ON people
    FOR EACH ROW EXECUTE FUNCTION invalidate_profile_cache_on_data_change();

CREATE TRIGGER trigger_invalidate_cache_on_music_change
    AFTER INSERT OR UPDATE OR DELETE ON music_tastes
    FOR EACH ROW EXECUTE FUNCTION invalidate_profile_cache_on_data_change();

CREATE TRIGGER trigger_invalidate_cache_on_food_change
    AFTER INSERT OR UPDATE OR DELETE ON food_tastes
    FOR EACH ROW EXECUTE FUNCTION invalidate_profile_cache_on_data_change();

CREATE TRIGGER trigger_invalidate_cache_on_movie_change
    AFTER INSERT OR UPDATE OR DELETE ON movie_tastes
    FOR EACH ROW EXECUTE FUNCTION invalidate_profile_cache_on_data_change();

-- Function to generate/update profile cache
CREATE OR REPLACE FUNCTION update_user_profile_cache(p_user_id UUID)
RETURNS VOID AS $$
BEGIN
    -- This would be called from the application layer
    -- to update the cached profile summaries
    INSERT INTO user_profile_cache (
        user_id,
        music_profile_summary,
        food_profile_summary,
        movie_profile_summary,
        relationship_insights,
        personality_summary,
        last_taste_update,
        last_people_update,
        last_behavior_update
    ) VALUES (
        p_user_id,
        'Generated by app layer',
        'Generated by app layer',
        'Generated by app layer',
        'Generated by app layer',
        'Generated by app layer',
        NOW(),
        NOW(),
        NOW()
    )
    ON CONFLICT (user_id) DO UPDATE SET
        updated_at = NOW(),
        data_version = user_profile_cache.data_version + 1;
END;
$$ LANGUAGE plpgsql;

COMMENT ON TABLE user_profile_cache IS 'Cached processed user profiles to optimize LLM token usage and reduce costs';
